-- =========================================================
-- 류현상 키우기
-- 2인 실시간 류현상 퀴즈 대전 Supabase 전체 설정
-- 이 내용을 전부 복사해서 SQL Editor에서 Run 하세요.
-- =========================================================


-- =========================================================
-- 1. 퀴즈 문제
-- =========================================================

create table if not exists public.quiz_questions (
  id integer generated by default as identity primary key,
  question text not null unique,
  options jsonb not null,
  correct_index smallint not null check (correct_index between 0 and 3)
);

-- 퀴즈 문제 테이블도 RLS 활성화
alter table public.quiz_questions enable row level security;



-- =========================================================
-- 2. 퀴즈 방
-- =========================================================

create table if not exists public.quiz_rooms (
  code text primary key,
  host_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'waiting'
    check (status in ('waiting','playing','finished')),
  question_ids integer[] not null default '{}',
  current_question integer not null default -1,
  question_started_at timestamptz,
  winner_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);



-- =========================================================
-- 3. 참가자
-- =========================================================

create table if not exists public.quiz_players (
  room_code text not null
    references public.quiz_rooms(code) on delete cascade,

  user_id uuid not null
    references auth.users(id) on delete cascade,

  nickname varchar(16) not null,

  ready boolean not null default false,

  score integer not null default 0,

  correct_count integer not null default 0,

  joined_at timestamptz not null default now(),

  left_at timestamptz,

  primary key (room_code, user_id)
);



-- =========================================================
-- 4. 답변 기록
-- =========================================================

create table if not exists public.quiz_answers (
  room_code text not null
    references public.quiz_rooms(code) on delete cascade,

  question_index integer not null,

  user_id uuid not null
    references auth.users(id) on delete cascade,

  answer_index smallint not null
    check (answer_index between 0 and 3),

  is_correct boolean not null,

  points integer not null default 0,

  answered_at timestamptz not null default now(),

  primary key (room_code, question_index, user_id)
);



-- =========================================================
-- 5. 류현상 퀴즈 문제 30개
-- =========================================================

insert into public.quiz_questions
(id, question, options, correct_index)
values

(1,
'기타를 담당하는 밴드 멤버는 누구일까?',
'["B군","L군","J군","R군"]'::jsonb,
0),

(2,
'B군은 류현상보다 몇 살 위일까?',
'["동갑","1살 위","2살 위","1살 아래"]'::jsonb,
1),

(3,
'B군이 주로 사용하는 말투는?',
'["서울 사투리","제주 사투리","부산 사투리","충청 사투리"]'::jsonb,
2),

(4,
'B군을 가장 잘 설명하는 생활 방식은?',
'["워커홀릭","낮잠 마니아","여행광","게임 폐인"]'::jsonb,
0),

(5,
'B군이 좋아하는 것은?',
'["해산물","술","단것","커피만"]'::jsonb,
1),

(6,
'L군이 담당하는 악기는?',
'["기타","베이스","피아노","드럼"]'::jsonb,
1),

(7,
'L군은 류현상과 어떤 인연이 있을까?',
'["친동생의 절친","군대 선임","고등학교 담임","전 기획사 대표"]'::jsonb,
0),

(8,
'L군의 성격에 가장 가까운 것은?',
'["유머러스하고 소프트함","극도로 과묵함","매우 냉정함","항상 화가 나 있음"]'::jsonb,
0),

(9,
'J군이 담당하는 악기는?',
'["드럼","베이스","피아노","기타"]'::jsonb,
2),

(10,
'평소 J군의 성격은?',
'["수다쟁이","과묵함","허풍쟁이","울보"]'::jsonb,
1),

(11,
'J군이 매우 무서워하고 먹지 못하는 것은?',
'["채소","고기","해산물","빵"]'::jsonb,
2),

(12,
'J군이 술을 마시면 어떻게 될까?',
'["더 조용해진다","바로 잔다","웃긴 미친놈 모드가 된다","노래만 한다"]'::jsonb,
2),

(13,
'R군이 담당하는 악기는?',
'["드럼","피아노","베이스","기타"]'::jsonb,
0),

(14,
'류현상의 매니저 이름은?',
'["후라보노","B군","나리","스칼레티아"]'::jsonb,
0),

(15,
'류현상의 기본 의상은?',
'["흰 티셔츠","검은 셔츠","군복","후드티"]'::jsonb,
1),

(16,
'공원 플리마켓은 기본적으로 며칠마다 열릴까?',
'["3일","5일","7일","10일"]'::jsonb,
2),

(17,
'플리마켓에서 물건이 아예 안 나올 확률은?',
'["5%","10%","20%","50%"]'::jsonb,
2),

(18,
'플리마켓 군복 착용 효과는?',
'["작곡 +10","편의점 알바·야간보조 체력 소모가 조금 감소","팬이 매일 증가","돈이 두 배로 벌림"]'::jsonb,
1),

(19,
'플리마켓 수건의 기능은?',
'["체력 회복","외모 증가","아무 기능 없음","스트레스 감소"]'::jsonb,
2),

(20,
'플리마켓 운동복의 특징은?',
'["외모가 아주 약간 증가","보컬 +20","돈 획득 증가","팬 감소"]'::jsonb,
0),

(21,
'강력한 다이어트알약은 기존 다이어트알약과 비교하면?',
'["효과만 2배","부작용만 2배","효과와 부작용 모두 2배","완전히 동일"]'::jsonb,
2),

(22,
'디지털 싱글 제작비는?',
'["300만원","500만원","1,000만원","2,000만원"]'::jsonb,
1),

(23,
'미니앨범 제작비는?',
'["500만원","1,000만원","2,000만원","5,000만원"]'::jsonb,
2),

(24,
'정규앨범 제작비는?',
'["2,000만원","3,000만원","5,000만원","1억원"]'::jsonb,
2),

(25,
'보컬 연습을 하지 않으면 마지막 연습 후 7일마다 어떻게 될까?',
'["보컬 -1","보컬 -2","보컬 -3","변화 없음"]'::jsonb,
1),

(26,
'작곡 연습을 하지 않으면 마지막 연습 후 7일마다 어떻게 될까?',
'["작곡 -2","작곡 -5","보컬 -2","변화 없음"]'::jsonb,
0),

(27,
'인지도 레벨의 최고 단계는?',
'["50","80","100","999"]'::jsonb,
2),

(28,
'스토커 이벤트가 시작될 수 있는 인지도 레벨은?',
'["20","30","40","70"]'::jsonb,
2),

(29,
'스토커 문제를 해결하지 못한 채 인지도 50레벨에 도달하면?',
'["월드스타 엔딩","스토커 살해 엔딩","파산 엔딩","아무 일 없음"]'::jsonb,
1),

(30,
'월드스타 엔딩에 필요한 팬 수 조건은?',
'["1만 명","5만 명","10만 명","100만 명"]'::jsonb,
2)

on conflict (id)
do update set
  question = excluded.question,
  options = excluded.options,
  correct_index = excluded.correct_index;



-- =========================================================
-- 6. 퀴즈 정답 직접 접근 차단
-- =========================================================

revoke all
on public.quiz_questions
from anon, authenticated;



-- =========================================================
-- 7. 참가 여부 확인 함수
-- =========================================================

create or replace function public.quiz_is_participant(
  p_room_code text
)
returns boolean

language sql

stable

security definer

set search_path = public

as $$

  select exists(

    select 1

    from public.quiz_players

    where room_code = p_room_code

      and user_id = auth.uid()

      and left_at is null

  );

$$;


revoke all
on function public.quiz_is_participant(text)
from public;


grant execute
on function public.quiz_is_participant(text)
to authenticated;



-- =========================================================
-- 8. RLS 활성화
-- =========================================================

alter table public.quiz_rooms
enable row level security;

alter table public.quiz_players
enable row level security;

alter table public.quiz_answers
enable row level security;



-- =========================================================
-- 9. RLS 정책 생성
-- 이미 있으면 오류 없이 넘어감
-- =========================================================


DO $$

BEGIN

  create policy "quiz_rooms_read"

  on public.quiz_rooms

  for select

  to authenticated

  using (
    public.quiz_is_participant(code)
  );

EXCEPTION

  WHEN duplicate_object THEN
    NULL;

END $$;



DO $$

BEGIN

  create policy "quiz_players_read"

  on public.quiz_players

  for select

  to authenticated

  using (
    public.quiz_is_participant(room_code)
  );

EXCEPTION

  WHEN duplicate_object THEN
    NULL;

END $$;



DO $$

BEGIN

  create policy "quiz_answers_read"

  on public.quiz_answers

  for select

  to authenticated

  using (
    public.quiz_is_participant(room_code)
  );

EXCEPTION

  WHEN duplicate_object THEN
    NULL;

END $$;



grant select
on public.quiz_rooms,
   public.quiz_players,
   public.quiz_answers
to authenticated;


revoke insert, update, delete
on public.quiz_rooms,
   public.quiz_players,
   public.quiz_answers
from anon, authenticated;



-- =========================================================
-- 10. 방 만들기
-- =========================================================

create or replace function public.quiz_create_room(
  p_nickname text
)

returns text

language plpgsql

security definer

set search_path = public

as $$

declare

  v_uid uuid := auth.uid();

  v_code text;

  i integer;

begin

  if v_uid is null then

    raise exception '로그인이 필요합니다.';

  end if;


  if nullif(trim(p_nickname),'') is null then

    raise exception '닉네임이 필요합니다.';

  end if;


  delete from public.quiz_rooms

  where created_at < now() - interval '2 hours';


  for i in 1..20 loop

    v_code := upper(

      substr(

        md5(
          random()::text ||
          clock_timestamp()::text ||
          v_uid::text
        ),

        1,

        6

      )

    );


    exit when not exists(

      select 1

      from public.quiz_rooms

      where code = v_code

    );

  end loop;


  if exists(

    select 1

    from public.quiz_rooms

    where code = v_code

  ) then

    raise exception '방 코드를 만들지 못했습니다.';

  end if;


  insert into public.quiz_rooms(
    code,
    host_id,
    status
  )

  values(
    v_code,
    v_uid,
    'waiting'
  );


  insert into public.quiz_players(
    room_code,
    user_id,
    nickname,
    ready
  )

  values(
    v_code,
    v_uid,
    left(trim(p_nickname),16),
    false
  );


  return v_code;

end;

$$;



-- =========================================================
-- 11. 방 참가
-- =========================================================

create or replace function public.quiz_join_room(
  p_code text,
  p_nickname text
)

returns text

language plpgsql

security definer

set search_path = public

as $$

declare

  v_uid uuid := auth.uid();

  v_code text := upper(trim(p_code));

  v_status text;

  v_count integer;

begin

  if v_uid is null then

    raise exception '로그인이 필요합니다.';

  end if;


  if nullif(trim(p_nickname),'') is null then

    raise exception '닉네임이 필요합니다.';

  end if;


  select status

  into v_status

  from public.quiz_rooms

  where code = v_code

  for update;


  if not found then

    raise exception '존재하지 않는 방 코드입니다.';

  end if;


  if v_status <> 'waiting' then

    raise exception '이미 시작했거나 종료된 방입니다.';

  end if;


  if exists(

    select 1

    from public.quiz_players

    where room_code = v_code

      and user_id = v_uid

  ) then


    update public.quiz_players

    set
      nickname = left(trim(p_nickname),16),
      left_at = null

    where room_code = v_code

      and user_id = v_uid;


    return v_code;

  end if;


  select count(*)

  into v_count

  from public.quiz_players

  where room_code = v_code

    and left_at is null;


  if v_count >= 2 then

    raise exception '이미 두 명이 참가한 방입니다.';

  end if;


  insert into public.quiz_players(
    room_code,
    user_id,
    nickname,
    ready
  )

  values(
    v_code,
    v_uid,
    left(trim(p_nickname),16),
    false
  );


  return v_code;

end;

$$;



-- =========================================================
-- 12. 준비 상태 변경
-- =========================================================

create or replace function public.quiz_set_ready(
  p_code text,
  p_ready boolean
)

returns void

language plpgsql

security definer

set search_path = public

as $$

declare

  v_uid uuid := auth.uid();

  v_status text;

begin


  select status

  into v_status

  from public.quiz_rooms

  where code = upper(trim(p_code));


  if v_status is null then

    raise exception '방을 찾을 수 없습니다.';

  end if;


  if v_status <> 'waiting' then

    raise exception '대기 중인 방에서만 준비할 수 있습니다.';

  end if;


  update public.quiz_players

  set ready = p_ready

  where room_code = upper(trim(p_code))

    and user_id = v_uid

    and left_at is null;


  if not found then

    raise exception '참가자가 아닙니다.';

  end if;

end;

$$;



-- =========================================================
-- 13. 대전 시작
-- 방장만 실행 가능
-- =========================================================

create or replace function public.quiz_start_room(
  p_code text
)

returns void

language plpgsql

security definer

set search_path = public

as $$

declare

  v_uid uuid := auth.uid();

  v_code text := upper(trim(p_code));

  v_host uuid;

  v_status text;

  v_players integer;

  v_ready integer;

  v_ids integer[];

begin


  select
    host_id,
    status

  into
    v_host,
    v_status

  from public.quiz_rooms

  where code = v_code

  for update;


  if not found then

    raise exception '방을 찾을 수 없습니다.';

  end if;


  if v_host <> v_uid then

    raise exception '방장만 시작할 수 있습니다.';

  end if;


  if v_status <> 'waiting' then

    raise exception '이미 시작된 방입니다.';

  end if;


  select
    count(*),
    count(*) filter(where ready)

  into
    v_players,
    v_ready

  from public.quiz_players

  where room_code = v_code

    and left_at is null;


  if v_players <> 2 then

    raise exception '두 명이 모두 입장해야 합니다.';

  end if;


  if v_ready <> 2 then

    raise exception '두 명 모두 준비해야 합니다.';

  end if;


  select array_agg(id order by rnd)

  into v_ids

  from (

    select
      id,
      random() as rnd

    from public.quiz_questions

    order by rnd

    limit 10

  ) q;


  if coalesce(array_length(v_ids,1),0) < 10 then

    raise exception '퀴즈 문제가 부족합니다.';

  end if;


  delete from public.quiz_answers

  where room_code = v_code;


  update public.quiz_players

  set
    score = 0,
    correct_count = 0,
    ready = false

  where room_code = v_code;


  update public.quiz_rooms

  set
    status = 'playing',
    question_ids = v_ids,
    current_question = 0,
    question_started_at = now(),
    winner_id = null,
    updated_at = now()

  where code = v_code;

end;

$$;



-- =========================================================
-- 14. 현재 문제 가져오기
-- 정답은 보내지 않음
-- =========================================================

create or replace function public.quiz_get_current_question(
  p_room_code text
)

returns table(

  question_no integer,

  question_id integer,

  question_text text,

  options jsonb,

  started_at timestamptz,

  room_status text

)

language plpgsql

security definer

set search_path = public

as $$

declare

  v_code text := upper(trim(p_room_code));

  v_idx integer;

  v_ids integer[];

  v_started timestamptz;

  v_status text;

  v_qid integer;

begin


  if not public.quiz_is_participant(v_code) then

    raise exception '참가자가 아닙니다.';

  end if;


  select
    current_question,
    question_ids,
    question_started_at,
    status

  into
    v_idx,
    v_ids,
    v_started,
    v_status

  from public.quiz_rooms

  where code = v_code;


  if not found then

    return;

  end if;


  if v_status <> 'playing'

     or v_idx < 0 then

    return;

  end if;


  v_qid := v_ids[v_idx + 1];


  return query

  select

    v_idx,

    q.id,

    q.question,

    q.options,

    v_started,

    v_status

  from public.quiz_questions q

  where q.id = v_qid;

end;

$$;



-- =========================================================
-- 15. 정답 제출
-- 점수와 정답은 서버에서 계산
-- =========================================================

create or replace function public.quiz_submit_answer(
  p_room_code text,
  p_question_index integer,
  p_answer_index integer
)

returns table(
  result_correct boolean,
  result_points integer,
  result_correct_index integer
)

language plpgsql

security definer

set search_path = public

as $$

declare

  v_uid uuid := auth.uid();

  v_code text := upper(trim(p_room_code));

  v_status text;

  v_idx integer;

  v_ids integer[];

  v_started timestamptz;

  v_qid integer;

  v_correct_idx integer;

  v_correct boolean;

  v_points integer := 0;

  v_correct_before integer := 0;

begin


  if p_answer_index not between 0 and 3 then

    raise exception '잘못된 답안입니다.';

  end if;


  if not public.quiz_is_participant(v_code) then

    raise exception '참가자가 아닙니다.';

  end if;


  select
    status,
    current_question,
    question_ids,
    question_started_at

  into
    v_status,
    v_idx,
    v_ids,
    v_started

  from public.quiz_rooms

  where code = v_code

  for update;


  if not found
     or v_status <> 'playing' then

    raise exception '진행 중인 대전이 아닙니다.';

  end if;


  if v_idx <> p_question_index then

    raise exception '이미 다음 문제로 넘어갔습니다.';

  end if;


  if now() > v_started + interval '12 seconds' then

    raise exception '답변 시간이 끝났습니다.';

  end if;


  if exists(

    select 1

    from public.quiz_answers

    where room_code = v_code

      and question_index = v_idx

      and user_id = v_uid

  ) then

    raise exception '이미 답을 제출했습니다.';

  end if;


  v_qid := v_ids[v_idx + 1];


  select correct_index

  into v_correct_idx

  from public.quiz_questions

  where id = v_qid;


  v_correct := (
    p_answer_index = v_correct_idx
  );


  if v_correct then


    select count(*)

    into v_correct_before

    from public.quiz_answers

    where room_code = v_code

      and question_index = v_idx

      and is_correct = true;


    v_points :=

      case

        when v_correct_before = 0
          then 100

        else 70

      end;

  end if;


  insert into public.quiz_answers(
    room_code,
    question_index,
    user_id,
    answer_index,
    is_correct,
    points
  )

  values(
    v_code,
    v_idx,
    v_uid,
    p_answer_index,
    v_correct,
    v_points
  );


  if v_correct then


    update public.quiz_players

    set
      score = score + v_points,

      correct_count =
        correct_count + 1

    where room_code = v_code

      and user_id = v_uid;

  end if;


  return query

  select

    v_correct,

    v_points,

    v_correct_idx;

end;

$$;



-- =========================================================
-- 16. 다음 문제로 이동
-- 둘 다 답하거나 12초가 지나면 이동
-- =========================================================

create or replace function public.quiz_advance_room(
  p_room_code text
)

returns text

language plpgsql

security definer

set search_path = public

as $$

declare

  v_code text :=
    upper(trim(p_room_code));

  v_status text;

  v_idx integer;

  v_ids integer[];

  v_started timestamptz;

  v_answered integer;

  v_players integer;

  v_top_score integer;

  v_top_count integer;

  v_winner uuid;

begin


  if not public.quiz_is_participant(v_code) then

    raise exception '참가자가 아닙니다.';

  end if;


  select
    status,
    current_question,
    question_ids,
    question_started_at

  into
    v_status,
    v_idx,
    v_ids,
    v_started

  from public.quiz_rooms

  where code = v_code

  for update;


  if not found then

    return 'missing';

  end if;


  if v_status <> 'playing' then

    return v_status;

  end if;


  select count(*)

  into v_players

  from public.quiz_players

  where room_code = v_code

    and left_at is null;


  select count(*)

  into v_answered

  from public.quiz_answers

  where room_code = v_code

    and question_index = v_idx;


  if v_answered < v_players

     and now() <
       v_started + interval '12 seconds'

  then

    return 'playing';

  end if;


  if v_idx >=
     coalesce(array_length(v_ids,1),0) - 1

  then


    select max(score)

    into v_top_score

    from public.quiz_players

    where room_code = v_code

      and left_at is null;


    select count(*)

    into v_top_count

    from public.quiz_players

    where room_code = v_code

      and left_at is null

      and score = v_top_score;


    if v_top_count = 1 then


      select user_id

      into v_winner

      from public.quiz_players

      where room_code = v_code

        and left_at is null

        and score = v_top_score

      limit 1;


    else

      v_winner := null;

    end if;


    update public.quiz_rooms

    set
      status = 'finished',
      winner_id = v_winner,
      updated_at = now()

    where code = v_code;


    return 'finished';

  end if;


  update public.quiz_rooms

  set
    current_question =
      v_idx + 1,

    question_started_at =
      now(),

    updated_at =
      now()

  where code = v_code;


  return 'playing';

end;

$$;



-- =========================================================
-- 17. 방 나가기
-- 진행 중 나가면 상대방 승리
-- =========================================================

create or replace function public.quiz_leave_room(
  p_room_code text
)

returns void

language plpgsql

security definer

set search_path = public

as $$

declare

  v_uid uuid := auth.uid();

  v_code text :=
    upper(trim(p_room_code));

  v_host uuid;

  v_status text;

  v_other uuid;

begin


  select
    host_id,
    status

  into
    v_host,
    v_status

  from public.quiz_rooms

  where code = v_code

  for update;


  if not found then

    return;

  end if;


  if not exists(

    select 1

    from public.quiz_players

    where room_code = v_code

      and user_id = v_uid

      and left_at is null

  ) then

    return;

  end if;


  if v_status = 'waiting' then


    if v_host = v_uid then

      delete from public.quiz_rooms

      where code = v_code;


    else


      delete from public.quiz_players

      where room_code = v_code

        and user_id = v_uid;


    end if;


    return;

  end if;


  if v_status = 'playing' then


    select user_id

    into v_other

    from public.quiz_players

    where room_code = v_code

      and user_id <> v_uid

      and left_at is null

    limit 1;


    update public.quiz_players

    set left_at = now()

    where room_code = v_code

      and user_id = v_uid;


    update public.quiz_rooms

    set
      status = 'finished',

      winner_id = v_other,

      updated_at = now()

    where code = v_code;


    return;

  end if;


  update public.quiz_players

  set left_at = now()

  where room_code = v_code

    and user_id = v_uid;

end;

$$;



-- =========================================================
-- 18. 함수 접근 권한 설정
-- =========================================================

revoke all
on function public.quiz_create_room(text)
from public;

revoke all
on function public.quiz_join_room(text,text)
from public;

revoke all
on function public.quiz_set_ready(text,boolean)
from public;

revoke all
on function public.quiz_start_room(text)
from public;

revoke all
on function public.quiz_get_current_question(text)
from public;

revoke all
on function public.quiz_submit_answer(text,integer,integer)
from public;

revoke all
on function public.quiz_advance_room(text)
from public;

revoke all
on function public.quiz_leave_room(text)
from public;



grant execute
on function public.quiz_create_room(text)
to authenticated;

grant execute
on function public.quiz_join_room(text,text)
to authenticated;

grant execute
on function public.quiz_set_ready(text,boolean)
to authenticated;

grant execute
on function public.quiz_start_room(text)
to authenticated;

grant execute
on function public.quiz_get_current_question(text)
to authenticated;

grant execute
on function public.quiz_submit_answer(text,integer,integer)
to authenticated;

grant execute
on function public.quiz_advance_room(text)
to authenticated;

grant execute
on function public.quiz_leave_room(text)
to authenticated;



-- =========================================================
-- 19. Supabase Realtime 등록
-- =========================================================

DO $$

BEGIN


  IF NOT EXISTS (

    SELECT 1

    FROM pg_publication_tables

    WHERE pubname =
      'supabase_realtime'

      AND schemaname =
      'public'

      AND tablename =
      'quiz_rooms'

  ) THEN


    ALTER PUBLICATION
      supabase_realtime

    ADD TABLE
      public.quiz_rooms;


  END IF;



  IF NOT EXISTS (

    SELECT 1

    FROM pg_publication_tables

    WHERE pubname =
      'supabase_realtime'

      AND schemaname =
      'public'

      AND tablename =
      'quiz_players'

  ) THEN


    ALTER PUBLICATION
      supabase_realtime

    ADD TABLE
      public.quiz_players;


  END IF;



  IF NOT EXISTS (

    SELECT 1

    FROM pg_publication_tables

    WHERE pubname =
      'supabase_realtime'

      AND schemaname =
      'public'

      AND tablename =
      'quiz_answers'

  ) THEN


    ALTER PUBLICATION
      supabase_realtime

    ADD TABLE
      public.quiz_answers;


  END IF;


END $$;



-- =========================================================
-- 20. Realtime 변경 데이터 전체 전달
-- =========================================================

alter table public.quiz_rooms
replica identity full;

alter table public.quiz_players
replica identity full;

alter table public.quiz_answers
replica identity full;



-- =========================================================
-- 완료
-- =========================================================

select '류현상 퀴즈 대전 DB 설정 완료!' as result;